# Setup
title: Ahmed "Nexusrex" Abutahoun
tagline: 'Portfolio'
description: Aspiring Game Programmer
url: "https://nexusrexdev.github.io"
baseurl: "" 
permalink: /blog/:categories/:year/:month/:day/:title/

# Blog & Excerpts
show_excerpts: true

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

# Custom Collections
collections:
  projects:
    output: true

# Build Settings & Plugins (Migrated from Blog)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-relative-links
  - jekyll-paginate

# Plugin Configurations
relative_links:
  enabled: true
  collections: true

# Exclusions to keep the build clean
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md